"""Is the generated per-shower FLOOR FRACTION under-dispersed? — the i.i.d. test.

Both calo heads are conditionally i.i.d. ACROSS CELLS given (particle embedding, sampled
globals): `PointCFM.sample` draws one Gaussian per cell and integrates each row independently,
`EnergyHead.sample` flips one at-floor Bernoulli per cell. The ONLY channel through which two
cells of the same shower know about each other is the shared 4-dim global draw
(total_logE, log_n, core_eta, core_phi).

That has a sharply testable consequence. Given a shower of n cells with per-cell floor
probability p, the number of at-floor cells k is Binomial(n, p) — variance EXACTLY n*p*(1-p).
Real showers should be OVER-dispersed relative to that, because a shower is compact-and-bright
or diffuse-and-fringy AS A WHOLE, correlated across all its cells at once. An i.i.d. sampler
cannot produce over-dispersion except through variation in its conditioning.

So the diagnostic is the DISPERSION RATIO, in bins of n:

    D = Var_obs(k | n) / (n * p_bar * (1 - p_bar))

  D_real >> 1 with D_gen ~ 1  -> STRUCTURAL. Cells must share information (a richer sampled
                                global, or an actual set model). More energy-head conditioning
                                cannot fix it — which would explain why `--energy_glob_idx 1`
                                moved frac_near_floor only 0.618 -> 0.574 (the mean, not the
                                variance).
  D_real ~ D_gen              -> NOT structural. The floor-fraction defect is a location/mean
                                problem and stays an energy-head conditioning question.

The test is CONSERVATIVE. Within one real shower p varies cell to cell (bright core vs faint
fringe), and a Poisson-binomial with heterogeneous p is UNDER-dispersed relative to
Binomial(n, p_bar), since sum p_i(1-p_i) <= n*p_bar(1-p_bar) by Jensen. Heterogeneity pushes
D_real DOWN, so an observed D_real > 1 is a LOWER BOUND on the real correlation.

`shower_width` is carried as a POSITIVE CONTROL. It is already believed to be i.i.d.-limited
(calo_metrics.py:39-40, calo_flow.py:490-492: "the shower-to-shower variation an i.i.d. point
model loses"), so a sound diagnostic must flag it too. Its i.i.d. null is the delta-method
sampling variance of the RMS over n independent cells,
    Var(width | n) = var(q) / (4 * n * mean(q)),   q = d_eta^2 + d_phi^2,
with var(q), mean(q) estimated from the pooled cells of that same n-bin.

Truth conditioning only; no training. Reads the same checkpoints calo_metrics.py scores.
"""
from __future__ import annotations
import argparse, json, sys
from pathlib import Path

import numpy as np
import torch

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
from genpu.flow.calo_flow import CaloFlow  # noqa: E402

PF_LOGPT, PF_ETA, PF_PHI, PF_PDG, PF_CHARGE, PF_MASS = range(6)
AUX_PRIMARY, AUX_PARENT, AUX_VX, AUX_VY, AUX_VZ, AUX_ENERGY = range(6)
CH_ETA, CH_PHI, CH_LOGE, CH_FRAC, CH_DET = range(5)

FLOOR_GEV = 5e-5          # zero-suppression threshold; must match build_calo_slice.FLOOR_GEV
FLOOR_MARGIN = 0.5        # "near floor" band in log-E; must match calo_metrics.event_features
# EnergyHead.floor_eps — the NARROW band its Bernoulli actually models. The wide FLOOR_MARGIN band
# above is what the gate scores, and it is generated by TWO different components: the Bernoulli's
# exact pile, and any mixture draw that lands low (including the physical sub-floor tail, which
# EnergyHead.loss deliberately leaves to the mixture). Reported separately below because attributing
# the whole band to the Bernoulli was wrong — the 2026-08-16 `--floor_n_buckets 32` run conditioned
# the Bernoulli on n and moved p(band | n=1) by 0.003.
FLOOR_EPS = 0.05

# dataviz reference palette, categorical slots 1 and 2 in fixed order (light mode).
C_REAL, C_GEN = "#2a78d6", "#eb6834"


def csr_gather(offsets, sel):
    """Cell indices for the selected showers + the shower index of each cell (CSR gather)."""
    n = (offsets[sel + 1] - offsets[sel]).astype(np.int64)
    tot = int(n.sum())
    shower_of_cell = np.repeat(np.arange(len(sel), dtype=np.int64), n)
    within = np.arange(tot, dtype=np.int64) - np.repeat(np.cumsum(n) - n, n)
    return np.repeat(offsets[sel].astype(np.int64), n) + within, shower_of_cell, n


def component_table(n_arr, comp, min_showers=200, n_max=24):
    """Split the near-floor band into its three generative components, per cells-per-shower bin.

    `comp` is a dict of per-shower COUNTS: sub (logE < floor-eps, the mixture's lower tail), pile
    (|logE-floor| <= eps, the Bernoulli), above (floor+eps < logE < floor+margin, the mixture's
    just-above draws). Their sum is the `frac_near_floor` band the gate scores. Which component owns
    the discrepancy decides whether the remaining fix is a Bernoulli problem at all.
    """
    rows = []
    for n in range(1, n_max + 1):
        m = n_arr == n
        cnt = int(m.sum())
        if cnt < min_showers:
            continue
        rows.append({"n": n, "showers": cnt,
                     **{k: round(float(v[m].sum() / (cnt * n)), 5) for k, v in comp.items()}})
    return rows


def dispersion_table(n_arr, k_arr, q_sum=None, q2_sum=None, width=None, min_showers=200,
                     n_max=24):
    """Per-n-bin over-dispersion of the at-floor COUNT (and, if given, of the width).

    Returns rows with the observed variance, the i.i.d. null, and their ratio.
    """
    rows = []
    for n in range(1, n_max + 1):
        m = n_arr == n
        cnt = int(m.sum())
        if cnt < min_showers:
            continue
        k = k_arr[m].astype(float)
        p = k.mean() / n
        var_binom = n * p * (1.0 - p)
        row = {"n": n, "showers": cnt, "p": round(float(p), 4),
               "var_obs": round(float(k.var()), 4), "var_iid": round(float(var_binom), 4),
               "D_floor": round(float(k.var() / var_binom), 3) if var_binom > 1e-12 else None}
        if width is not None and n >= 2:
            w = width[m].astype(float)
            # pooled per-cell q statistics for these showers -> delta-method null on the RMS
            mq = float(q_sum[m].sum() / (cnt * n))
            # E[q^2] per cell, then Var(q)
            mq2 = float(q2_sum[m].sum() / (cnt * n))
            vq = max(mq2 - mq * mq, 1e-30)
            var_w_iid = vq / (4.0 * n * max(mq, 1e-30))
            row |= {"var_w_obs": float(f"{w.var():.4g}"), "var_w_iid": float(f"{var_w_iid:.4g}"),
                    "D_width": round(float(w.var() / var_w_iid), 3)}
        rows.append(row)
    return rows


def pooled_D(rows, key):
    """Shower-weighted mean dispersion ratio across the n-bins."""
    v = [(r["showers"], r[key]) for r in rows if r.get(key) is not None]
    if not v:
        return None
    w = np.array([a for a, _ in v], float); d = np.array([b for _, b in v], float)
    return float((w * d).sum() / w.sum())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ckpt", required=True)
    ap.add_argument("--pdg_class", type=int, nargs="+", default=[3, 4])
    ap.add_argument("--shard", type=int, default=5, help="HELD-OUT shard (train used 0-2)")
    ap.add_argument("--preproc_dir", default="/scratch/gpfs/IOJALVO/lv7805/genpu_data/preprocessed")
    ap.add_argument("--n", type=int, default=300000, help="subsample this many showers")
    ap.add_argument("--steps", type=int, default=50)
    ap.add_argument("--batch", type=int, default=200000)
    ap.add_argument("--tag", default="pion")
    ap.add_argument("--anchor_kind", choices=["helix", "line", "auto"], default="helix",
                    help="must MATCH the slice the checkpoint was trained on")
    ap.add_argument("--geometry", default=None)
    ap.add_argument("--no_partition", action="store_true",
                    help="match the setting calo_metrics.py was run with for this checkpoint")
    ap.add_argument("--no_econs", action="store_true")
    ap.add_argument("--outdir", default="/home/lv7805/genpu/plots/calo/metrics")
    ap.add_argument("--no_plot", action="store_true")
    args = ap.parse_args()

    dev = "cuda" if torch.cuda.is_available() else "cpu"
    torch.manual_seed(0); rng = np.random.default_rng(0)

    # ---- model (same load path as calo_metrics.py) ----
    ckpt = torch.load(args.ckpt, map_location=dev, weights_only=False)
    sd = ckpt["model"]; src_ = ckpt.get("norm", sd)

    def _get(base):
        for k in (f"cont_{base}", f"cond_{base}"):
            if k in src_:
                v = src_[k]
                return v.cpu().numpy() if hasattr(v, "cpu") else np.asarray(v)
        raise KeyError(base)

    norm = {"cont_mean": _get("mean"), "cont_std": _get("std")}
    for k in ["glob_mean", "glob_std", "pts_mean", "pts_std"]:
        v = src_[k]; norm[k] = v.cpu().numpy() if hasattr(v, "cpu") else np.asarray(v)
    model, missing, unexpected = CaloFlow.from_checkpoint(sd, norm)
    model = model.to(dev).eval()
    print(f"loaded {args.ckpt}\n  partition={not args.no_partition}  "
          f"core_anchored={bool(model.core_anchored > 0)}  anchor_cond={model.anchor_cond}")

    # ---- data ----
    d = np.load(Path(args.preproc_dir) / f"shard_{args.shard:04d}_stage2.npz")
    pf, aux, ch, off = d["particle_features"], d["particle_aux"], d["calo_hits_flat"], d["calo_offsets"]
    ncal = np.diff(off)
    sel = np.where(np.isin(pf[:, PF_PDG], args.pdg_class) & (ncal >= 1))[0]
    if len(sel) > args.n:
        sel = np.sort(rng.choice(sel, args.n, replace=False))
    print(f"shard {args.shard}: {len(sel)} showers, pdg_class {args.pdg_class}")

    vr = np.hypot(aux[sel, AUX_VX], aux[sel, AUX_VY])
    logE = np.log(np.clip(aux[sel, AUX_ENERGY], 1e-6, None))
    cont = np.stack([pf[sel, PF_LOGPT], pf[sel, PF_ETA], logE, pf[sel, PF_CHARGE],
                     pf[sel, PF_MASS], vr, aux[sel, AUX_VZ]], 1).astype(np.float32)
    pdg = pf[sel, PF_PDG].astype(np.int64)
    p_eta, p_phi = pf[sel, PF_ETA], pf[sel, PF_PHI]
    E_true = aux[sel, AUX_ENERGY].astype(np.float32)

    contS = torch.as_tensor((cont - norm["cont_mean"]) / norm["cont_std"], device=dev)
    pdgT = torch.as_tensor(pdg, device=dev)
    E_trueT = torch.as_tensor(E_true, device=dev)

    anchorT = modeT = None
    if bool(model.core_anchored > 0):
        from genpu.calo_geom import core_anchor as anchor_of, load_front_face
        R_face, Z_face = load_front_face(args.geometry)
        a_eta, a_phi, a_mode = anchor_of(np.exp(pf[sel, PF_LOGPT]), p_phi, p_eta, pf[sel, PF_CHARGE],
                                         aux[sel, AUX_VX], aux[sel, AUX_VY], aux[sel, AUX_VZ],
                                         R_face, Z_face, kind=args.anchor_kind)
        modeT = torch.as_tensor(a_mode.astype(np.int64), device=dev)
        anchorT = torch.as_tensor(np.stack([a_eta, a_phi], 1), dtype=torch.float32, device=dev)
        print(f"core anchor ON ({args.anchor_kind}), branches "
              f"{ {lab: round(float((a_mode == c).mean()), 3) for c, lab in [(0,'barrel'),(1,'endcap'),(2,'turning'),(3,'none')]} }")

    # ---- REAL per-shower: n, at-floor count, width, and the q moments for the width null ----
    thr = np.log(FLOOR_GEV) + FLOOR_MARGIN
    cidx, sofc, r_n = csr_gather(off, sel)
    r_logE = ch[cidx, CH_LOGE].astype(np.float64)
    r_k = np.bincount(sofc, weights=(r_logE < thr).astype(np.float64), minlength=len(sel))
    lf = np.log(FLOOR_GEV)
    r_comp = {k: np.bincount(sofc, weights=v.astype(np.float64), minlength=len(sel)) for k, v in
              (("sub", r_logE < lf - FLOOR_EPS),
               ("pile", np.abs(r_logE - lf) <= FLOOR_EPS),
               ("above", (r_logE > lf + FLOOR_EPS) & (r_logE < thr)))}
    de = ch[cidx, CH_ETA] - p_eta[sofc]; dp = ch[cidx, CH_PHI] - p_phi[sofc]
    q = (de ** 2 + dp ** 2).astype(np.float64)
    r_qs = np.bincount(sofc, weights=q, minlength=len(sel))
    r_q2s = np.bincount(sofc, weights=q * q, minlength=len(sel))
    r_width = np.sqrt(r_qs / np.maximum(r_n, 1))
    del cidx, sofc, r_logE, de, dp, q

    # ---- GENERATED ----
    g_k = np.zeros(len(sel)); g_n = np.zeros(len(sel))
    g_qs = np.zeros(len(sel)); g_q2s = np.zeros(len(sel))
    g_comp = {k: np.zeros(len(sel)) for k in ("sub", "pile", "above")}
    for s in range(0, len(sel), args.batch):
        e = min(s + args.batch, len(sel))
        with torch.no_grad():
            sh = model.sample_showers(contS[s:e], pdgT[s:e], steps=args.steps,
                                      partition=not args.no_partition,
                                      e_true=None if args.no_econs else E_trueT[s:e],
                                      core_anchor=None if anchorT is None else anchorT[s:e],
                                      anchor_mode=None if modeT is None else modeT[s:e])
        rep = sh["src"].cpu().numpy() + s
        gl = sh["logE"].cpu().numpy().astype(np.float64)
        pos = sh["pos"].cpu().numpy(); core = sh["core"].cpu().numpy()
        # cells are deltas from the shower core, which is itself an offset from the particle:
        # the same construction calo_metrics.py uses, so `width` is the same observable
        gde = core[sh["src"].cpu().numpy(), 0] + pos[:, 0]
        gdp = core[sh["src"].cpu().numpy(), 1] + pos[:, 1]
        gq = (gde ** 2 + gdp ** 2).astype(np.float64)
        g_n += np.bincount(rep, minlength=len(sel))
        g_k += np.bincount(rep, weights=(gl < thr).astype(np.float64), minlength=len(sel))
        for k_, v_ in (("sub", gl < lf - FLOOR_EPS), ("pile", np.abs(gl - lf) <= FLOOR_EPS),
                       ("above", (gl > lf + FLOOR_EPS) & (gl < thr))):
            g_comp[k_] += np.bincount(rep, weights=v_.astype(np.float64), minlength=len(sel))
        g_qs += np.bincount(rep, weights=gq, minlength=len(sel))
        g_q2s += np.bincount(rep, weights=gq * gq, minlength=len(sel))
    g_width = np.sqrt(g_qs / np.maximum(g_n, 1))

    # ---- report ----
    rf_r = r_k / np.maximum(r_n, 1); rf_g = g_k / np.maximum(g_n, 1)
    print(f"\nper-shower floor fraction   real mean {rf_r.mean():.4f} std {rf_r.std():.4f}"
          f"   |   gen mean {rf_g.mean():.4f} std {rf_g.std():.4f}"
          f"   (std ratio gen/real {rf_g.std()/max(rf_r.std(),1e-12):.3f})")
    print(f"cells/shower                real mean {r_n.mean():.2f}   gen mean {g_n.mean():.2f}")

    rows_r = dispersion_table(r_n, r_k, r_qs, r_q2s, r_width)
    rows_g = dispersion_table(g_n.astype(np.int64), g_k, g_qs, g_q2s, g_width)
    by_n_g = {r["n"]: r for r in rows_g}

    print(f"\nOVER-DISPERSION vs the i.i.d. null, per cells/shower bin"
          f"   (D=1 is what conditionally-independent cells can produce)")
    print(f"{'n':>4} {'showers':>9} {'p_real':>7} {'p_gen':>7} "
          f"{'D_floor real':>13} {'D_floor gen':>12} {'D_width real':>13} {'D_width gen':>12}")
    for r in rows_r:
        g = by_n_g.get(r["n"], {})
        def f(x, w=12):
            return f"{x:>{w}.3f}" if isinstance(x, (int, float)) else f"{'-':>{w}}"
        print(f"{r['n']:>4} {r['showers']:>9} {r['p']:>7.3f} {g.get('p', float('nan')):>7.3f} "
              f"{f(r.get('D_floor'), 13)} {f(g.get('D_floor'))} "
              f"{f(r.get('D_width'), 13)} {f(g.get('D_width'))}")

    # ---- WHICH COMPONENT owns the near-floor band ----
    comp_r = component_table(r_n, r_comp)
    comp_g = component_table(g_n.astype(np.int64), g_comp)
    cg = {r["n"]: r for r in comp_g}
    print(f"\nWHICH COMPONENT owns the near-floor band, per cells/shower bin")
    print(f"  sub = mixture draw below floor-eps | pile = the Bernoulli | above = mixture just above")
    print(f"{'n':>4} {'showers':>9} {'sub real':>9} {'sub gen':>8} {'pile real':>10} {'pile gen':>9} "
          f"{'above real':>11} {'above gen':>10}")
    for r in comp_r:
        g = cg.get(r["n"], {})
        print(f"{r['n']:>4} {r['showers']:>9} {r['sub']:>9.4f} {g.get('sub', float('nan')):>8.4f} "
              f"{r['pile']:>10.4f} {g.get('pile', float('nan')):>9.4f} "
              f"{r['above']:>11.4f} {g.get('above', float('nan')):>10.4f}")
    tot = lambda rows, k: sum(r["showers"] * r[k] for r in rows) / max(sum(r["showers"] for r in rows), 1)
    print(f"  pooled  sub {tot(comp_r,'sub'):.4f}/{tot(comp_g,'sub'):.4f}  "
          f"pile {tot(comp_r,'pile'):.4f}/{tot(comp_g,'pile'):.4f}  "
          f"above {tot(comp_r,'above'):.4f}/{tot(comp_g,'above'):.4f}   (real/gen)")

    out = {"tag": args.tag, "ckpt": args.ckpt, "pdg_class": args.pdg_class, "shard": args.shard,
           "components_real": comp_r, "components_gen": comp_g,
           "n_showers": int(len(sel)),
           "floor_frac": {"real_mean": float(rf_r.mean()), "real_std": float(rf_r.std()),
                          "gen_mean": float(rf_g.mean()), "gen_std": float(rf_g.std()),
                          "std_ratio_gen_real": float(rf_g.std() / max(rf_r.std(), 1e-12))},
           "cells_per_shower": {"real_mean": float(r_n.mean()), "gen_mean": float(g_n.mean())},
           "pooled": {"D_floor_real": pooled_D(rows_r, "D_floor"),
                      "D_floor_gen": pooled_D(rows_g, "D_floor"),
                      "D_width_real": pooled_D(rows_r, "D_width"),
                      "D_width_gen": pooled_D(rows_g, "D_width")},
           "by_n_real": rows_r, "by_n_gen": rows_g}

    pf_ = out["pooled"]
    print(f"\nPOOLED (shower-weighted):  D_floor real {pf_['D_floor_real']:.3f} vs gen "
          f"{pf_['D_floor_gen']:.3f}   |   D_width real {pf_['D_width_real']:.3f} vs gen "
          f"{pf_['D_width_gen']:.3f}")
    verdict = ("STRUCTURAL — real cells are correlated, generated cells are not"
               if pf_["D_floor_real"] > 1.5 * max(pf_["D_floor_gen"], 1e-9)
               else "NOT structural on the floor count — mean/conditioning problem")
    out["verdict"] = verdict
    print(f"VERDICT: {verdict}")

    o = Path(args.outdir); o.mkdir(parents=True, exist_ok=True)
    (o / f"floor_dispersion_{args.tag}.json").write_text(json.dumps(out, indent=2))
    print("wrote", o / f"floor_dispersion_{args.tag}.json")

    if not args.no_plot:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        fig, ax = plt.subplots(1, 2, figsize=(11, 4.2))
        bins = np.linspace(0, 1, 51)
        for a_, lab, c in ((rf_r, "real", C_REAL), (rf_g, "generated", C_GEN)):
            ax[0].hist(a_, bins=bins, histtype="step", lw=2, color=c, label=lab, density=True)
        ax[0].set_xlabel("per-shower floor fraction"); ax[0].set_ylabel("density")
        ax[0].set_title(f"{args.tag}: floor fraction per shower")
        ax[0].legend(frameon=False)
        for rows, lab, c in ((rows_r, "real", C_REAL), (rows_g, "generated", C_GEN)):
            xs = [r["n"] for r in rows if r.get("D_floor") is not None]
            ys = [r["D_floor"] for r in rows if r.get("D_floor") is not None]
            ax[1].plot(xs, ys, "-o", lw=2, ms=5, color=c, label=lab)
        ax[1].axhline(1.0, color="#888888", lw=1, ls="--")
        ax[1].annotate("i.i.d. floor", (0.98, 1.0), xycoords=("axes fraction", "data"),
                       ha="right", va="bottom", color="#666666", fontsize=9)
        ax[1].set_xlabel("cells per shower"); ax[1].set_ylabel("Var(k) / n·p(1−p)")
        ax[1].set_title("over-dispersion of the at-floor count")
        ax[1].legend(frameon=False)
        for a_ in ax:
            a_.grid(alpha=0.25, lw=0.6); a_.set_axisbelow(True)
            for sp in ("top", "right"):
                a_.spines[sp].set_visible(False)
        fig.tight_layout()
        p = o / f"floor_dispersion_{args.tag}.png"
        fig.savefig(p, dpi=140); print("wrote", p)


if __name__ == "__main__":
    main()
